sudo: false
language: go
go:
- 1.x
branches:
  except:
  - "/^v\\d+[.]\\d+[.]\\d+.*/"
script:
- make ci-trigger
env:
  global:
    secure: AXmCyw4tVVBKJNS9UGThf+4rAwZ8NecLMXIdZfIvuuDnt5GQJdsiXRgv4/TqFImWBttLEkLlCSUC8Q2Of6qBDKznAVjOuxwWgPY8D9TteDkUqpdgy7ade6Y9d2FIetjujFDD9gBdpvE0OJaeFrTkmw+RGepxvxvJcI8weYnkFDB8Fy+lWh51OyHUcdEgXo/iMncfcI1yxwhgO9ze7C5FR3+vfti6a18QOq4AgfJW8FmCd2f8xp7USr258v0exyMBrCKQYWYoyDC8m+Fi9u0NKecSaQj5qLjG3f+Yk8BXFlJgw6KOBrf4Uofrv4g2z81s0cK+Kd4I59KPUf8TGsayhc62i+MZ94TqC8VU91KlbHKtv4J8F/0uDxpRaRTVUDIhnQLxviGnq5z3CYYhe2W1s/GyvvD9MTwD7tm6W7LQQakXYBghQezHprwGoGYNwI9WxJa1TFV7MK39swNOT5JWhWG9o68avRC96bJfqeXjWoY49Nk7qex/8LlpMfMW/U+azcW+hZ6xICWEWaA/uapjY97ZpYdYsMMoz+vy48lzrXpwg60Kww4C60hmN+o8MfIdCuNznw1QPUd0qd1HaqkyEIp+qkrCl2Ufhrbt13zi2KqSOMDXDfiTPbRgr+wD59zC6DHMPMAG5h+emrnsUl/uyKbcGUW/plKjR+2lyqMkl58=
