/*
This file was generated by treerack (https://github.com/aryszka/treerack).

The contents of this file fall under different licenses.

The code between the "// head" and "// eo head" lines falls under the same
license as the source code of treerack (https://github.com/aryszka/treerack),
unless explicitly stated otherwise, if treerack's license allows changing the
license of this source code.

Treerack's license: MIT https://opensource.org/licenses/MIT
where YEAR=2018, COPYRIGHT HOLDER=Arpad Ryszka (arpad.ryszka@gmail.com)

The rest of the content of this file falls under the same license as the one
that the user of treerack generating this file declares for it, or it is
unlicensed.
*/

package self

import (
	"bufio"
	"errors"
	"fmt"
	"io"
	"strconv"
	"strings"
	"unicode"
)

type charParser struct {
	name   string
	id     int
	not    bool
	chars  []rune
	ranges [][]rune
}
type charBuilder struct {
	name string
	id   int
}

func (p *charParser) nodeName() string {
	return p.name
}
func (p *charParser) nodeID() int {
	return p.id
}
func (p *charParser) commitType() CommitType {
	return Alias
}
func matchChar(chars []rune, ranges [][]rune, not bool, char rune) bool {
	for _, ci := range chars {
		if ci == char {
			return !not
		}
	}
	for _, ri := range ranges {
		if char >= ri[0] && char <= ri[1] {
			return !not
		}
	}
	return not
}
func (p *charParser) match(t rune) bool {
	return matchChar(p.chars, p.ranges, p.not, t)
}
func (p *charParser) parse(c *context) {
	if tok, ok := c.token(); !ok || !p.match(tok) {
		if c.offset > c.failOffset {
			c.failOffset = c.offset
			c.failingParser = nil
		}
		c.fail(c.offset)
		return
	}
	c.success(c.offset + 1)
}
func (b *charBuilder) nodeName() string {
	return b.name
}
func (b *charBuilder) nodeID() int {
	return b.id
}
func (b *charBuilder) build(c *context) ([]*Node, bool) {
	return nil, false
}

type sequenceParser struct {
	name            string
	id              int
	commit          CommitType
	items           []parser
	ranges          [][]int
	generalizations []int
	allChars        bool
}
type sequenceBuilder struct {
	name     string
	id       int
	commit   CommitType
	items    []builder
	ranges   [][]int
	allChars bool
}

func (p *sequenceParser) nodeName() string {
	return p.name
}
func (p *sequenceParser) nodeID() int {
	return p.id
}
func (p *sequenceParser) commitType() CommitType {
	return p.commit
}
func (p *sequenceParser) parse(c *context) {
	if !p.allChars {
		if c.results.pending(c.offset, p.id) {
			c.fail(c.offset)
			return
		}
		c.results.markPending(c.offset, p.id)
	}
	var (
		currentCount int
		parsed       bool
	)
	itemIndex := 0
	from := c.offset
	to := c.offset
	for itemIndex < len(p.items) {
		p.items[itemIndex].parse(c)
		if !c.matchLast {
			if currentCount >= p.ranges[itemIndex][0] {
				itemIndex++
				currentCount = 0
				continue
			}
			if c.failingParser == nil && p.commit&userDefined != 0 && p.commit&Whitespace == 0 && p.commit&FailPass == 0 {
				c.failingParser = p
			}
			c.fail(from)
			if !p.allChars {
				c.results.unmarkPending(from, p.id)
			}
			return
		}
		parsed = c.offset > to
		if parsed {
			currentCount++
		}
		to = c.offset
		if !parsed || p.ranges[itemIndex][1] > 0 && currentCount == p.ranges[itemIndex][1] {
			itemIndex++
			currentCount = 0
		}
	}
	for _, g := range p.generalizations {
		if c.results.pending(from, g) {
			c.results.setMatch(from, g, to)
		}
	}
	if to > c.failOffset {
		c.failOffset = -1
		c.failingParser = nil
	}
	c.results.setMatch(from, p.id, to)
	c.success(to)
	if !p.allChars {
		c.results.unmarkPending(from, p.id)
	}
}
func (b *sequenceBuilder) nodeName() string {
	return b.name
}
func (b *sequenceBuilder) nodeID() int {
	return b.id
}
func (b *sequenceBuilder) build(c *context) ([]*Node, bool) {
	to, ok := c.results.longestMatch(c.offset, b.id)
	if !ok {
		return nil, false
	}
	from := c.offset
	parsed := to > from
	if b.allChars {
		c.offset = to
		if b.commit&Alias != 0 {
			return nil, true
		}
		return []*Node{{Name: b.name, From: from, To: to, tokens: c.tokens}}, true
	} else if parsed {
		c.results.dropMatchTo(c.offset, b.id, to)
	} else {
		if c.results.pending(c.offset, b.id) {
			return nil, false
		}
		c.results.markPending(c.offset, b.id)
	}
	var (
		itemIndex    int
		currentCount int
		nodes        []*Node
	)
	for itemIndex < len(b.items) {
		itemFrom := c.offset
		n, ok := b.items[itemIndex].build(c)
		if !ok {
			itemIndex++
			currentCount = 0
			continue
		}
		if c.offset > itemFrom {
			nodes = append(nodes, n...)
			currentCount++
			if b.ranges[itemIndex][1] > 0 && currentCount == b.ranges[itemIndex][1] {
				itemIndex++
				currentCount = 0
			}
			continue
		}
		if currentCount < b.ranges[itemIndex][0] {
			for i := 0; i < b.ranges[itemIndex][0]-currentCount; i++ {
				nodes = append(nodes, n...)
			}
		}
		itemIndex++
		currentCount = 0
	}
	if !parsed {
		c.results.unmarkPending(from, b.id)
	}
	if b.commit&Alias != 0 {
		return nodes, true
	}
	return []*Node{{Name: b.name, From: from, To: to, Nodes: nodes, tokens: c.tokens}}, true
}

type choiceParser struct {
	name            string
	id              int
	commit          CommitType
	options         []parser
	generalizations []int
}
type choiceBuilder struct {
	name    string
	id      int
	commit  CommitType
	options []builder
}

func (p *choiceParser) nodeName() string {
	return p.name
}
func (p *choiceParser) nodeID() int {
	return p.id
}
func (p *choiceParser) commitType() CommitType {
	return p.commit
}
func (p *choiceParser) parse(c *context) {
	if c.fromResults(p) {
		return
	}
	if c.results.pending(c.offset, p.id) {
		c.fail(c.offset)
		return
	}
	c.results.markPending(c.offset, p.id)
	var (
		match         bool
		optionIndex   int
		foundMatch    bool
		failingParser parser
	)
	from := c.offset
	to := c.offset
	initialFailOffset := c.failOffset
	initialFailingParser := c.failingParser
	failOffset := initialFailOffset
	for {
		foundMatch = false
		optionIndex = 0
		for optionIndex < len(p.options) {
			p.options[optionIndex].parse(c)
			optionIndex++
			if !c.matchLast {
				if c.failOffset > failOffset {
					failOffset = c.failOffset
					failingParser = c.failingParser
				}
			}
			if !c.matchLast || match && c.offset <= to {
				c.offset = from
				continue
			}
			match = true
			foundMatch = true
			to = c.offset
			c.offset = from
			c.results.setMatch(from, p.id, to)
		}
		if !foundMatch {
			break
		}
	}
	if match {
		if failOffset > to {
			c.failOffset = failOffset
			c.failingParser = failingParser
		} else if to > initialFailOffset {
			c.failOffset = -1
			c.failingParser = nil
		} else {
			c.failOffset = initialFailOffset
			c.failingParser = initialFailingParser
		}
		c.success(to)
		c.results.unmarkPending(from, p.id)
		return
	}
	if failOffset > initialFailOffset {
		c.failOffset = failOffset
		c.failingParser = failingParser
		if c.failingParser == nil && p.commitType()&userDefined != 0 && p.commitType()&Whitespace == 0 && p.commitType()&FailPass == 0 {
			c.failingParser = p
		}
	}
	c.results.setNoMatch(from, p.id)
	c.fail(from)
	c.results.unmarkPending(from, p.id)
}
func (b *choiceBuilder) nodeName() string {
	return b.name
}
func (b *choiceBuilder) nodeID() int {
	return b.id
}
func (b *choiceBuilder) build(c *context) ([]*Node, bool) {
	to, ok := c.results.longestMatch(c.offset, b.id)
	if !ok {
		return nil, false
	}
	from := c.offset
	parsed := to > from
	if parsed {
		c.results.dropMatchTo(c.offset, b.id, to)
	} else {
		if c.results.pending(c.offset, b.id) {
			return nil, false
		}
		c.results.markPending(c.offset, b.id)
	}
	var option builder
	for _, o := range b.options {
		if c.results.hasMatchTo(c.offset, o.nodeID(), to) {
			option = o
			break
		}
	}
	n, _ := option.build(c)
	if !parsed {
		c.results.unmarkPending(from, b.id)
	}
	if b.commit&Alias != 0 {
		return n, true
	}
	return []*Node{{Name: b.name, From: from, To: to, Nodes: n, tokens: c.tokens}}, true
}

type idSet struct{ ids []uint }

func divModBits(id int) (int, int) {
	return id / strconv.IntSize, id % strconv.IntSize
}
func (s *idSet) set(id int) {
	d, m := divModBits(id)
	if d >= len(s.ids) {
		if d < cap(s.ids) {
			s.ids = s.ids[:d+1]
		} else {
			s.ids = s.ids[:cap(s.ids)]
			for i := cap(s.ids); i <= d; i++ {
				s.ids = append(s.ids, 0)
			}
		}
	}
	s.ids[d] |= 1 << uint(m)
}
func (s *idSet) unset(id int) {
	d, m := divModBits(id)
	if d >= len(s.ids) {
		return
	}
	s.ids[d] &^= 1 << uint(m)
}
func (s *idSet) has(id int) bool {
	d, m := divModBits(id)
	if d >= len(s.ids) {
		return false
	}
	return s.ids[d]&(1<<uint(m)) != 0
}

type results struct {
	noMatch   []*idSet
	match     [][]int
	isPending [][]int
}

func ensureOffsetInts(ints [][]int, offset int) [][]int {
	if len(ints) > offset {
		return ints
	}
	if cap(ints) > offset {
		ints = ints[:offset+1]
		return ints
	}
	ints = ints[:cap(ints)]
	for i := len(ints); i <= offset; i++ {
		ints = append(ints, nil)
	}
	return ints
}
func ensureOffsetIDs(ids []*idSet, offset int) []*idSet {
	if len(ids) > offset {
		return ids
	}
	if cap(ids) > offset {
		ids = ids[:offset+1]
		return ids
	}
	ids = ids[:cap(ids)]
	for i := len(ids); i <= offset; i++ {
		ids = append(ids, nil)
	}
	return ids
}
func (r *results) setMatch(offset, id, to int) {
	r.match = ensureOffsetInts(r.match, offset)
	for i := 0; i < len(r.match[offset]); i += 2 {
		if r.match[offset][i] != id || r.match[offset][i+1] != to {
			continue
		}
		return
	}
	r.match[offset] = append(r.match[offset], id, to)
}
func (r *results) setNoMatch(offset, id int) {
	if len(r.match) > offset {
		for i := 0; i < len(r.match[offset]); i += 2 {
			if r.match[offset][i] != id {
				continue
			}
			return
		}
	}
	r.noMatch = ensureOffsetIDs(r.noMatch, offset)
	if r.noMatch[offset] == nil {
		r.noMatch[offset] = &idSet{}
	}
	r.noMatch[offset].set(id)
}
func (r *results) hasMatchTo(offset, id, to int) bool {
	if len(r.match) <= offset {
		return false
	}
	for i := 0; i < len(r.match[offset]); i += 2 {
		if r.match[offset][i] != id {
			continue
		}
		if r.match[offset][i+1] == to {
			return true
		}
	}
	return false
}
func (r *results) longestMatch(offset, id int) (int, bool) {
	if len(r.match) <= offset {
		return 0, false
	}
	var found bool
	to := -1
	for i := 0; i < len(r.match[offset]); i += 2 {
		if r.match[offset][i] != id {
			continue
		}
		if r.match[offset][i+1] > to {
			to = r.match[offset][i+1]
		}
		found = true
	}
	return to, found
}
func (r *results) longestResult(offset, id int) (int, bool, bool) {
	if len(r.noMatch) > offset && r.noMatch[offset] != nil && r.noMatch[offset].has(id) {
		return 0, false, true
	}
	to, ok := r.longestMatch(offset, id)
	return to, ok, ok
}
func (r *results) dropMatchTo(offset, id, to int) {
	for i := 0; i < len(r.match[offset]); i += 2 {
		if r.match[offset][i] != id {
			continue
		}
		if r.match[offset][i+1] == to {
			r.match[offset][i] = -1
			return
		}
	}
}
func (r *results) resetPending() {
	r.isPending = nil
}
func (r *results) pending(offset, id int) bool {
	if len(r.isPending) <= id {
		return false
	}
	for i := range r.isPending[id] {
		if r.isPending[id][i] == offset {
			return true
		}
	}
	return false
}
func (r *results) markPending(offset, id int) {
	r.isPending = ensureOffsetInts(r.isPending, id)
	for i := range r.isPending[id] {
		if r.isPending[id][i] == -1 {
			r.isPending[id][i] = offset
			return
		}
	}
	r.isPending[id] = append(r.isPending[id], offset)
}
func (r *results) unmarkPending(offset, id int) {
	for i := range r.isPending[id] {
		if r.isPending[id][i] == offset {
			r.isPending[id][i] = -1
			break
		}
	}
}

type context struct {
	reader        io.RuneReader
	offset        int
	readOffset    int
	consumed      int
	failOffset    int
	failingParser parser
	readErr       error
	eof           bool
	results       *results
	tokens        []rune
	matchLast     bool
}

func newContext(r io.RuneReader) *context {
	return &context{reader: r, results: &results{}, failOffset: -1}
}
func (c *context) read() bool {
	if c.eof || c.readErr != nil {
		return false
	}
	token, n, err := c.reader.ReadRune()
	if err != nil {
		if err == io.EOF {
			if n == 0 {
				c.eof = true
				return false
			}
		} else {
			c.readErr = err
			return false
		}
	}
	c.readOffset++
	if token == unicode.ReplacementChar {
		c.readErr = ErrInvalidUnicodeCharacter
		return false
	}
	c.tokens = append(c.tokens, token)
	return true
}
func (c *context) token() (rune, bool) {
	if c.offset == c.readOffset {
		if !c.read() {
			return 0, false
		}
	}
	return c.tokens[c.offset], true
}
func (c *context) fromResults(p parser) bool {
	to, m, ok := c.results.longestResult(c.offset, p.nodeID())
	if !ok {
		return false
	}
	if m {
		c.success(to)
	} else {
		c.fail(c.offset)
	}
	return true
}
func (c *context) success(to int) {
	c.offset = to
	c.matchLast = true
	if to > c.consumed {
		c.consumed = to
	}
}
func (c *context) fail(offset int) {
	c.offset = offset
	c.matchLast = false
}
func findLine(tokens []rune, offset int) (line, column int) {
	tokens = tokens[:offset]
	for i := range tokens {
		column++
		if tokens[i] == '\n' {
			column = 0
			line++
		}
	}
	return
}
func (c *context) parseError(p parser) error {
	definition := p.nodeName()
	flagIndex := strings.Index(definition, ":")
	if flagIndex > 0 {
		definition = definition[:flagIndex]
	}
	if c.failingParser == nil {
		c.failOffset = c.consumed
	}
	line, col := findLine(c.tokens, c.failOffset)
	return &ParseError{Offset: c.failOffset, Line: line, Column: col, Definition: definition}
}
func (c *context) finalizeParse(root parser) error {
	fp := c.failingParser
	if fp == nil {
		fp = root
	}
	to, match, found := c.results.longestResult(0, root.nodeID())
	if !found || !match || found && match && to < c.readOffset {
		return c.parseError(fp)
	}
	c.read()
	if c.eof {
		return nil
	}
	if c.readErr != nil {
		return c.readErr
	}
	return c.parseError(root)
}

type Node struct {
	Name     string
	Nodes    []*Node
	From, To int
	tokens   []rune
}

func (n *Node) Tokens() []rune {
	defer func() {
		if err := recover(); err != nil {
			println(len(n.tokens), n.From, n.To)
			panic(err)
		}
	}()
	return n.tokens
}
func (n *Node) String() string {
	return fmt.Sprintf("%s:%d:%d:%s", n.Name, n.From, n.To, n.Text())
}
func (n *Node) Text() string {
	return string(n.Tokens()[n.From:n.To])
}

type CommitType int

const (
	None  CommitType = 0
	Alias CommitType = 1 << iota
	Whitespace
	NoWhitespace
	FailPass
	Root
	userDefined
)

type formatFlags int

const (
	formatNone   formatFlags = 0
	formatPretty formatFlags = 1 << iota
	formatIncludeComments
)

type ParseError struct {
	Input      string
	Offset     int
	Line       int
	Column     int
	Definition string
}
type parser interface {
	nodeName() string
	nodeID() int
	commitType() CommitType
	parse(*context)
}
type builder interface {
	nodeName() string
	nodeID() int
	build(*context) ([]*Node, bool)
}

var ErrInvalidUnicodeCharacter = errors.New("invalid unicode character")

func (pe *ParseError) Error() string {
	return fmt.Sprintf("%s:%d:%d:parse failed, parsing: %s", pe.Input, pe.Line+1, pe.Column+1, pe.Definition)
}
func parse(r io.Reader, p parser, b builder) (*Node, error) {
	c := newContext(bufio.NewReader(r))
	p.parse(c)
	if c.readErr != nil {
		return nil, c.readErr
	}
	if err := c.finalizeParse(p); err != nil {
		if perr, ok := err.(*ParseError); ok {
			perr.Input = "<input>"
		}
		return nil, err
	}
	c.offset = 0
	c.results.resetPending()
	n, _ := b.build(c)
	return n[0], nil
}

func Parse(r io.Reader) (*Node, error) {
	var p188 = sequenceParser{id: 188, commit: 32, allChars: false, ranges: [][]int{{0, -1}, {1, 1}, {0, -1}}, generalizations: []int{}}
	var p186 = choiceParser{id: 186, commit: 2, generalizations: []int{}}
	var p185 = choiceParser{id: 185, commit: 70, name: "wsc", generalizations: []int{186}}
	var p17 = choiceParser{id: 17, commit: 66, name: "wschar", generalizations: []int{185, 186}}
	var p109 = sequenceParser{id: 109, commit: 10, allChars: true, ranges: [][]int{{1, 1}, {1, 1}}, generalizations: []int{17, 185, 186}}
	var p108 = charParser{id: 108, not: false, chars: []rune{32}, ranges: [][]rune{}}
	p109.items = []parser{&p108}
	var p170 = sequenceParser{id: 170, commit: 10, allChars: true, ranges: [][]int{{1, 1}, {1, 1}}, generalizations: []int{17, 185, 186}}
	var p137 = charParser{id: 137, not: false, chars: []rune{9}, ranges: [][]rune{}}
	p170.items = []parser{&p137}
	var p54 = sequenceParser{id: 54, commit: 10, allChars: true, ranges: [][]int{{1, 1}, {1, 1}}, generalizations: []int{17, 185, 186}}
	var p147 = charParser{id: 147, not: false, chars: []rune{10}, ranges: [][]rune{}}
	p54.items = []parser{&p147}
	var p64 = sequenceParser{id: 64, commit: 10, allChars: true, ranges: [][]int{{1, 1}, {1, 1}}, generalizations: []int{17, 185, 186}}
	var p157 = charParser{id: 157, not: false, chars: []rune{8}, ranges: [][]rune{}}
	p64.items = []parser{&p157}
	var p72 = sequenceParser{id: 72, commit: 10, allChars: true, ranges: [][]int{{1, 1}, {1, 1}}, generalizations: []int{17, 185, 186}}
	var p121 = charParser{id: 121, not: false, chars: []rune{12}, ranges: [][]rune{}}
	p72.items = []parser{&p121}
	var p19 = sequenceParser{id: 19, commit: 10, allChars: true, ranges: [][]int{{1, 1}, {1, 1}}, generalizations: []int{17, 185, 186}}
	var p16 = charParser{id: 16, not: false, chars: []rune{13}, ranges: [][]rune{}}
	p19.items = []parser{&p16}
	var p5 = sequenceParser{id: 5, commit: 10, allChars: true, ranges: [][]int{{1, 1}, {1, 1}}, generalizations: []int{17, 185, 186}}
	var p73 = charParser{id: 73, not: false, chars: []rune{11}, ranges: [][]rune{}}
	p5.items = []parser{&p73}
	p17.options = []parser{&p109, &p170, &p54, &p64, &p72, &p19, &p5}
	var p58 = sequenceParser{id: 58, commit: 72, allChars: false, name: "comment", ranges: [][]int{{1, 1}, {0, -1}, {1, 1}, {0, -1}}, generalizations: []int{185, 186}}
	var p43 = choiceParser{id: 43, commit: 74, name: "comment-segment", generalizations: []int{}}
	var p144 = sequenceParser{id: 144, commit: 74, allChars: false, name: "line-comment", ranges: [][]int{{1, 1}, {0, -1}, {1, 1}, {0, -1}}, generalizations: []int{43}}
	var p138 = sequenceParser{id: 138, commit: 10, allChars: true, ranges: [][]int{{1, 1}, {1, 1}, {1, 1}, {1, 1}}, generalizations: []int{}}
	var p42 = charParser{id: 42, not: false, chars: []rune{47}, ranges: [][]rune{}}
	var p35 = charParser{id: 35, not: false, chars: []rune{47}, ranges: [][]rune{}}
	p138.items = []parser{&p42, &p35}
	var p30 = sequenceParser{id: 30, commit: 10, allChars: true, ranges: [][]int{{1, 1}, {1, 1}}, generalizations: []int{}}
	var p166 = charParser{id: 166, not: true, chars: []rune{10}, ranges: [][]rune{}}
	p30.items = []parser{&p166}
	p144.items = []parser{&p138, &p30}
	var p90 = sequenceParser{id: 90, commit: 74, allChars: false, name: "block-comment", ranges: [][]int{{1, 1}, {0, -1}, {1, 1}, {1, 1}, {0, -1}, {1, 1}}, generalizations: []int{43}}
	var p129 = sequenceParser{id: 129, commit: 10, allChars: true, ranges: [][]int{{1, 1}, {1, 1}, {1, 1}, {1, 1}}, generalizations: []int{}}
	var p158 = charParser{id: 158, not: false, chars: []rune{47}, ranges: [][]rune{}}
	var p95 = charParser{id: 95, not: false, chars: []rune{42}, ranges: [][]rune{}}
	p129.items = []parser{&p158, &p95}
	var p6 = choiceParser{id: 6, commit: 10, generalizations: []int{}}
	var p153 = sequenceParser{id: 153, commit: 10, allChars: false, ranges: [][]int{{1, 1}, {1, 1}, {1, 1}, {1, 1}}, generalizations: []int{6}}
	var p101 = sequenceParser{id: 101, commit: 10, allChars: true, ranges: [][]int{{1, 1}, {1, 1}}, generalizations: []int{}}
	var p148 = charParser{id: 148, not: false, chars: []rune{42}, ranges: [][]rune{}}
	p101.items = []parser{&p148}
	var p13 = sequenceParser{id: 13, commit: 10, allChars: true, ranges: [][]int{{1, 1}, {1, 1}}, generalizations: []int{}}
	var p142 = charParser{id: 142, not: true, chars: []rune{47}, ranges: [][]rune{}}
	p13.items = []parser{&p142}
	p153.items = []parser{&p101, &p13}
	var p143 = sequenceParser{id: 143, commit: 10, allChars: true, ranges: [][]int{{1, 1}, {1, 1}}, generalizations: []int{6}}
	var p83 = charParser{id: 83, not: true, chars: []rune{42}, ranges: [][]rune{}}
	p143.items = []parser{&p83}
	p6.options = []parser{&p153, &p143}
	var p89 = sequenceParser{id: 89, commit: 10, allChars: true, ranges: [][]int{{1, 1}, {1, 1}, {1, 1}, {1, 1}}, generalizations: []int{}}
	var p96 = charParser{id: 96, not: false, chars: []rune{42}, ranges: [][]rune{}}
	var p130 = charParser{id: 130, not: false, chars: []rune{47}, ranges: [][]rune{}}
	p89.items = []parser{&p96, &p130}
	p90.items = []parser{&p129, &p6, &p89}
	p43.options = []parser{&p144, &p90}
	var p31 = sequenceParser{id: 31, commit: 10, allChars: false, ranges: [][]int{{0, -1}, {0, 1}, {0, -1}, {1, 1}, {0, -1}, {0, 1}, {0, -1}, {1, 1}}, generalizations: []int{}}
	var p57 = choiceParser{id: 57, commit: 74, name: "ws-no-nl", generalizations: []int{}}
	var p50 = sequenceParser{id: 50, commit: 10, allChars: true, ranges: [][]int{{1, 1}, {1, 1}}, generalizations: []int{57}}
	var p167 = charParser{id: 167, not: false, chars: []rune{32}, ranges: [][]rune{}}
	p50.items = []parser{&p167}
	var p151 = sequenceParser{id: 151, commit: 10, allChars: true, ranges: [][]int{{1, 1}, {1, 1}}, generalizations: []int{57}}
	var p114 = charParser{id: 114, not: false, chars: []rune{9}, ranges: [][]rune{}}
	p151.items = []parser{&p114}
	var p145 = sequenceParser{id: 145, commit: 10, allChars: true, ranges: [][]int{{1, 1}, {1, 1}}, generalizations: []int{57}}
	var p36 = charParser{id: 36, not: false, chars: []rune{8}, ranges: [][]rune{}}
	p145.items = []parser{&p36}
	var p140 = sequenceParser{id: 140, commit: 10, allChars: true, ranges: [][]int{{1, 1}, {1, 1}}, generalizations: []int{57}}
	var p122 = charParser{id: 122, not: false, chars: []rune{12}, ranges: [][]rune{}}
	p140.items = []parser{&p122}
	var p178 = sequenceParser{id: 178, commit: 10, allChars: true, ranges: [][]int{{1, 1}, {1, 1}}, generalizations: []int{57}}
	var p77 = charParser{id: 77, not: false, chars: []rune{13}, ranges: [][]rune{}}
	p178.items = []parser{&p77}
	var p66 = sequenceParser{id: 66, commit: 10, allChars: true, ranges: [][]int{{1, 1}, {1, 1}}, generalizations: []int{57}}
	var p37 = charParser{id: 37, not: false, chars: []rune{11}, ranges: [][]rune{}}
	p66.items = []parser{&p37}
	p57.options = []parser{&p50, &p151, &p145, &p140, &p178, &p66}
	var p141 = sequenceParser{id: 141, commit: 10, allChars: true, ranges: [][]int{{1, 1}, {1, 1}}, generalizations: []int{}}
	var p51 = charParser{id: 51, not: false, chars: []rune{10}, ranges: [][]rune{}}
	p141.items = []parser{&p51}
	p31.items = []parser{&p57, &p141, &p57, &p43}
	p58.items = []parser{&p43, &p31}
	p185.options = []parser{&p17, &p58}
	p186.options = []parser{&p185}
	var p187 = sequenceParser{id: 187, commit: 66, allChars: false, name: "syntax:wsroot", ranges: [][]int{{0, 1}, {0, -1}, {0, 1}, {0, 1}}, generalizations: []int{}}
	var p182 = sequenceParser{id: 182, commit: 2, allChars: false, ranges: [][]int{{1, 1}, {0, -1}}, generalizations: []int{}}
	var p120 = sequenceParser{id: 120, commit: 10, allChars: true, ranges: [][]int{{1, 1}, {1, 1}}, generalizations: []int{}}
	var p119 = charParser{id: 119, not: false, chars: []rune{59}, ranges: [][]rune{}}
	p120.items = []parser{&p119}
	var p181 = sequenceParser{id: 181, commit: 2, allChars: false, ranges: [][]int{{0, -1}, {1, 1}}, generalizations: []int{}}
	p181.items = []parser{&p186, &p120}
	p182.items = []parser{&p120, &p181}
	var p165 = sequenceParser{id: 165, commit: 66, allChars: false, name: "definitions", ranges: [][]int{{1, 1}, {0, 1}}, generalizations: []int{}}
	var p46 = sequenceParser{id: 46, commit: 64, allChars: false, name: "definition", ranges: [][]int{{1, 1}, {0, -1}, {1, 1}, {0, -1}, {1, 1}}, generalizations: []int{}}
	var p18 = sequenceParser{id: 18, commit: 74, allChars: false, name: "definition-name", ranges: [][]int{{1, 1}, {0, -1}, {1, 1}, {0, -1}}, generalizations: []int{}}
	var p8 = sequenceParser{id: 8, commit: 72, allChars: false, name: "symbol", ranges: [][]int{{1, -1}, {1, -1}}, generalizations: []int{15, 21, 171}}
	var p7 = sequenceParser{id: 7, commit: 10, allChars: true, ranges: [][]int{{1, 1}, {1, 1}}, generalizations: []int{}}
	var p154 = charParser{id: 154, not: true, chars: []rune{92, 32, 10, 9, 8, 12, 13, 11, 47, 46, 91, 93, 34, 123, 125, 94, 43, 42, 63, 124, 40, 41, 58, 61, 59}, ranges: [][]rune{}}
	p7.items = []parser{&p154}
	p8.items = []parser{&p7}
	var p24 = sequenceParser{id: 24, commit: 10, allChars: false, ranges: [][]int{{1, 1}, {1, 1}, {1, 1}, {1, 1}}, generalizations: []int{}}
	var p69 = sequenceParser{id: 69, commit: 10, allChars: true, ranges: [][]int{{1, 1}, {1, 1}}, generalizations: []int{}}
	var p162 = charParser{id: 162, not: false, chars: []rune{58}, ranges: [][]rune{}}
	p69.items = []parser{&p162}
	var p56 = choiceParser{id: 56, commit: 66, name: "flag", generalizations: []int{}}
	var p169 = sequenceParser{id: 169, commit: 72, allChars: true, name: "alias", ranges: [][]int{{1, 1}, {1, 1}, {1, 1}, {1, 1}, {1, 1}, {1, 1}, {1, 1}, {1, 1}, {1, 1}, {1, 1}}, generalizations: []int{56}}
	var p175 = charParser{id: 175, not: false, chars: []rune{97}, ranges: [][]rune{}}
	var p68 = charParser{id: 68, not: false, chars: []rune{108}, ranges: [][]rune{}}
	var p4 = charParser{id: 4, not: false, chars: []rune{105}, ranges: [][]rune{}}
	var p22 = charParser{id: 22, not: false, chars: []rune{97}, ranges: [][]rune{}}
	var p97 = charParser{id: 97, not: false, chars: []rune{115}, ranges: [][]rune{}}
	p169.items = []parser{&p175, &p68, &p4, &p22, &p97}
	var p11 = sequenceParser{id: 11, commit: 72, allChars: true, name: "ws", ranges: [][]int{{1, 1}, {1, 1}, {1, 1}, {1, 1}}, generalizations: []int{56}}
	var p150 = charParser{id: 150, not: false, chars: []rune{119}, ranges: [][]rune{}}
	var p45 = charParser{id: 45, not: false, chars: []rune{115}, ranges: [][]rune{}}
	p11.items = []parser{&p150, &p45}
	var p23 = sequenceParser{id: 23, commit: 72, allChars: true, name: "nows", ranges: [][]int{{1, 1}, {1, 1}, {1, 1}, {1, 1}, {1, 1}, {1, 1}, {1, 1}, {1, 1}}, generalizations: []int{56}}
	var p136 = charParser{id: 136, not: false, chars: []rune{110}, ranges: [][]rune{}}
	var p55 = charParser{id: 55, not: false, chars: []rune{111}, ranges: [][]rune{}}
	var p33 = charParser{id: 33, not: false, chars: []rune{119}, ranges: [][]rune{}}
	var p39 = charParser{id: 39, not: false, chars: []rune{115}, ranges: [][]rune{}}
	p23.items = []parser{&p136, &p55, &p33, &p39}
	var p12 = sequenceParser{id: 12, commit: 72, allChars: true, name: "failpass", ranges: [][]int{{1, 1}, {1, 1}, {1, 1}, {1, 1}, {1, 1}, {1, 1}, {1, 1}, {1, 1}, {1, 1}, {1, 1}, {1, 1}, {1, 1}, {1, 1}, {1, 1}, {1, 1}, {1, 1}}, generalizations: []int{56}}
	var p81 = charParser{id: 81, not: false, chars: []rune{102}, ranges: [][]rune{}}
	var p62 = charParser{id: 62, not: false, chars: []rune{97}, ranges: [][]rune{}}
	var p156 = charParser{id: 156, not: false, chars: []rune{105}, ranges: [][]rune{}}
	var p74 = charParser{id: 74, not: false, chars: []rune{108}, ranges: [][]rune{}}
	var p118 = charParser{id: 118, not: false, chars: []rune{112}, ranges: [][]rune{}}
	var p40 = charParser{id: 40, not: false, chars: []rune{97}, ranges: [][]rune{}}
	var p75 = charParser{id: 75, not: false, chars: []rune{115}, ranges: [][]rune{}}
	var p113 = charParser{id: 113, not: false, chars: []rune{115}, ranges: [][]rune{}}
	p12.items = []parser{&p81, &p62, &p156, &p74, &p118, &p40, &p75, &p113}
	var p29 = sequenceParser{id: 29, commit: 72, allChars: true, name: "root", ranges: [][]int{{1, 1}, {1, 1}, {1, 1}, {1, 1}, {1, 1}, {1, 1}, {1, 1}, {1, 1}}, generalizations: []int{56}}
	var p76 = charParser{id: 76, not: false, chars: []rune{114}, ranges: [][]rune{}}
	var p176 = charParser{id: 176, not: false, chars: []rune{111}, ranges: [][]rune{}}
	var p107 = charParser{id: 107, not: false, chars: []rune{111}, ranges: [][]rune{}}
	var p128 = charParser{id: 128, not: false, chars: []rune{116}, ranges: [][]rune{}}
	p29.items = []parser{&p76, &p176, &p107, &p128}
	p56.options = []parser{&p169, &p11, &p23, &p12, &p29}
	p24.items = []parser{&p69, &p56}
	p18.items = []parser{&p8, &p24}
	var p177 = sequenceParser{id: 177, commit: 10, allChars: true, ranges: [][]int{{1, 1}, {1, 1}}, generalizations: []int{}}
	var p63 = charParser{id: 63, not: false, chars: []rune{61}, ranges: [][]rune{}}
	p177.items = []parser{&p63}
	var p15 = choiceParser{id: 15, commit: 66, name: "expression", generalizations: []int{}}
	var p88 = choiceParser{id: 88, commit: 66, name: "terminal", generalizations: []int{15, 21, 171}}
	var p179 = sequenceParser{id: 179, commit: 72, allChars: true, name: "any-char", ranges: [][]int{{1, 1}, {1, 1}}, generalizations: []int{88, 15, 21, 171}}
	var p67 = charParser{id: 67, not: false, chars: []rune{46}, ranges: [][]rune{}}
	p179.items = []parser{&p67}
	var p173 = sequenceParser{id: 173, commit: 72, allChars: false, name: "char-class", ranges: [][]int{{1, 1}, {0, 1}, {0, -1}, {1, 1}, {1, 1}, {0, 1}, {0, -1}, {1, 1}}, generalizations: []int{88, 15, 21, 171}}
	var p131 = sequenceParser{id: 131, commit: 10, allChars: true, ranges: [][]int{{1, 1}, {1, 1}}, generalizations: []int{}}
	var p20 = charParser{id: 20, not: false, chars: []rune{91}, ranges: [][]rune{}}
	p131.items = []parser{&p20}
	var p87 = sequenceParser{id: 87, commit: 72, allChars: true, name: "class-not", ranges: [][]int{{1, 1}, {1, 1}}, generalizations: []int{}}
	var p91 = charParser{id: 91, not: false, chars: []rune{94}, ranges: [][]rune{}}
	p87.items = []parser{&p91}
	var p110 = choiceParser{id: 110, commit: 10, generalizations: []int{}}
	var p65 = choiceParser{id: 65, commit: 72, name: "class-char", generalizations: []int{110}}
	var p1 = sequenceParser{id: 1, commit: 10, allChars: true, ranges: [][]int{{1, 1}, {1, 1}}, generalizations: []int{65, 110}}
	var p102 = charParser{id: 102, not: true, chars: []rune{92, 91, 93, 94, 45}, ranges: [][]rune{}}
	p1.items = []parser{&p102}
	var p38 = sequenceParser{id: 38, commit: 10, allChars: false, ranges: [][]int{{1, 1}, {1, 1}, {1, 1}, {1, 1}}, generalizations: []int{65, 110}}
	var p116 = sequenceParser{id: 116, commit: 10, allChars: true, ranges: [][]int{{1, 1}, {1, 1}}, generalizations: []int{}}
	var p28 = charParser{id: 28, not: false, chars: []rune{92}, ranges: [][]rune{}}
	p116.items = []parser{&p28}
	var p172 = sequenceParser{id: 172, commit: 10, allChars: true, ranges: [][]int{{1, 1}, {1, 1}}, generalizations: []int{}}
	var p123 = charParser{id: 123, not: true, chars: []rune{}, ranges: [][]rune{}}
	p172.items = []parser{&p123}
	p38.items = []parser{&p116, &p172}
	p65.options = []parser{&p1, &p38}
	var p117 = sequenceParser{id: 117, commit: 72, allChars: false, name: "char-range", ranges: [][]int{{1, 1}, {1, 1}, {1, 1}, {1, 1}, {1, 1}, {1, 1}}, generalizations: []int{110}}
	var p159 = sequenceParser{id: 159, commit: 10, allChars: true, ranges: [][]int{{1, 1}, {1, 1}}, generalizations: []int{}}
	var p115 = charParser{id: 115, not: false, chars: []rune{45}, ranges: [][]rune{}}
	p159.items = []parser{&p115}
	p117.items = []parser{&p65, &p159, &p65}
	p110.options = []parser{&p65, &p117}
	var p103 = sequenceParser{id: 103, commit: 10, allChars: true, ranges: [][]int{{1, 1}, {1, 1}}, generalizations: []int{}}
	var p132 = charParser{id: 132, not: false, chars: []rune{93}, ranges: [][]rune{}}
	p103.items = []parser{&p132}
	p173.items = []parser{&p131, &p87, &p110, &p103}
	var p3 = sequenceParser{id: 3, commit: 72, allChars: false, name: "char-sequence", ranges: [][]int{{1, 1}, {0, -1}, {1, 1}, {1, 1}, {0, -1}, {1, 1}}, generalizations: []int{88, 15, 21, 171}}
	var p152 = sequenceParser{id: 152, commit: 10, allChars: true, ranges: [][]int{{1, 1}, {1, 1}}, generalizations: []int{}}
	var p84 = charParser{id: 84, not: false, chars: []rune{34}, ranges: [][]rune{}}
	p152.items = []parser{&p84}
	var p52 = choiceParser{id: 52, commit: 72, name: "sequence-char", generalizations: []int{}}
	var p32 = sequenceParser{id: 32, commit: 10, allChars: true, ranges: [][]int{{1, 1}, {1, 1}}, generalizations: []int{52}}
	var p14 = charParser{id: 14, not: true, chars: []rune{92, 34}, ranges: [][]rune{}}
	p32.items = []parser{&p14}
	var p160 = sequenceParser{id: 160, commit: 10, allChars: false, ranges: [][]int{{1, 1}, {1, 1}, {1, 1}, {1, 1}}, generalizations: []int{52}}
	var p2 = sequenceParser{id: 2, commit: 10, allChars: true, ranges: [][]int{{1, 1}, {1, 1}}, generalizations: []int{}}
	var p124 = charParser{id: 124, not: false, chars: []rune{92}, ranges: [][]rune{}}
	p2.items = []parser{&p124}
	var p133 = sequenceParser{id: 133, commit: 10, allChars: true, ranges: [][]int{{1, 1}, {1, 1}}, generalizations: []int{}}
	var p47 = charParser{id: 47, not: true, chars: []rune{}, ranges: [][]rune{}}
	p133.items = []parser{&p47}
	p160.items = []parser{&p2, &p133}
	p52.options = []parser{&p32, &p160}
	var p125 = sequenceParser{id: 125, commit: 10, allChars: true, ranges: [][]int{{1, 1}, {1, 1}}, generalizations: []int{}}
	var p48 = charParser{id: 48, not: false, chars: []rune{34}, ranges: [][]rune{}}
	p125.items = []parser{&p48}
	p3.items = []parser{&p152, &p52, &p125}
	p88.options = []parser{&p179, &p173, &p3}
	var p174 = sequenceParser{id: 174, commit: 66, allChars: false, name: "group", ranges: [][]int{{1, 1}, {0, -1}, {1, 1}, {0, -1}, {1, 1}}, generalizations: []int{15, 21, 171}}
	var p85 = sequenceParser{id: 85, commit: 10, allChars: true, ranges: [][]int{{1, 1}, {1, 1}}, generalizations: []int{}}
	var p149 = charParser{id: 149, not: false, chars: []rune{40}, ranges: [][]rune{}}
	p85.items = []parser{&p149}
	var p25 = sequenceParser{id: 25, commit: 10, allChars: true, ranges: [][]int{{1, 1}, {1, 1}}, generalizations: []int{}}
	var p79 = charParser{id: 79, not: false, chars: []rune{41}, ranges: [][]rune{}}
	p25.items = []parser{&p79}
	p174.items = []parser{&p85, &p186, &p15, &p186, &p25}
	var p106 = sequenceParser{id: 106, commit: 64, allChars: false, name: "sequence", ranges: [][]int{{1, 1}, {0, -1}}, generalizations: []int{15, 171}}
	var p61 = sequenceParser{id: 61, commit: 72, allChars: false, name: "item", ranges: [][]int{{1, 1}, {0, 1}, {1, 1}, {0, 1}}, generalizations: []int{}}
	var p21 = choiceParser{id: 21, commit: 10, generalizations: []int{}}
	p21.options = []parser{&p88, &p8, &p174}
	var p10 = choiceParser{id: 10, commit: 66, name: "quantity", generalizations: []int{}}
	var p139 = sequenceParser{id: 139, commit: 64, allChars: false, name: "count-quantifier", ranges: [][]int{{1, 1}, {0, -1}, {1, 1}, {0, -1}, {1, 1}}, generalizations: []int{10}}
	var p27 = sequenceParser{id: 27, commit: 10, allChars: true, ranges: [][]int{{1, 1}, {1, 1}}, generalizations: []int{}}
	var p9 = charParser{id: 9, not: false, chars: []rune{123}, ranges: [][]rune{}}
	p27.items = []parser{&p9}
	var p86 = sequenceParser{id: 86, commit: 64, allChars: false, name: "count", ranges: [][]int{{1, 1}}, generalizations: []int{}}
	var p92 = sequenceParser{id: 92, commit: 74, allChars: false, name: "number", ranges: [][]int{{1, -1}, {1, -1}}, generalizations: []int{}}
	var p134 = sequenceParser{id: 134, commit: 10, allChars: true, ranges: [][]int{{1, 1}, {1, 1}}, generalizations: []int{}}
	var p126 = charParser{id: 126, not: false, chars: []rune{}, ranges: [][]rune{{48, 57}}}
	p134.items = []parser{&p126}
	p92.items = []parser{&p134}
	p86.items = []parser{&p92}
	var p93 = sequenceParser{id: 93, commit: 10, allChars: true, ranges: [][]int{{1, 1}, {1, 1}}, generalizations: []int{}}
	var p78 = charParser{id: 78, not: false, chars: []rune{125}, ranges: [][]rune{}}
	p93.items = []parser{&p78}
	p139.items = []parser{&p27, &p186, &p86, &p186, &p93}
	var p146 = sequenceParser{id: 146, commit: 64, allChars: false, name: "range-quantifier", ranges: [][]int{{1, 1}, {0, -1}, {0, 1}, {0, -1}, {1, 1}, {0, -1}, {0, 1}, {0, -1}, {1, 1}}, generalizations: []int{10}}
	var p44 = sequenceParser{id: 44, commit: 10, allChars: true, ranges: [][]int{{1, 1}, {1, 1}}, generalizations: []int{}}
	var p94 = charParser{id: 94, not: false, chars: []rune{123}, ranges: [][]rune{}}
	p44.items = []parser{&p94}
	var p127 = sequenceParser{id: 127, commit: 64, allChars: false, name: "range-from", ranges: [][]int{{1, 1}}, generalizations: []int{}}
	p127.items = []parser{&p92}
	var p49 = sequenceParser{id: 49, commit: 10, allChars: true, ranges: [][]int{{1, 1}, {1, 1}}, generalizations: []int{}}
	var p59 = charParser{id: 59, not: false, chars: []rune{44}, ranges: [][]rune{}}
	p49.items = []parser{&p59}
	var p26 = sequenceParser{id: 26, commit: 64, allChars: false, name: "range-to", ranges: [][]int{{1, 1}}, generalizations: []int{}}
	p26.items = []parser{&p92}
	var p135 = sequenceParser{id: 135, commit: 10, allChars: true, ranges: [][]int{{1, 1}, {1, 1}}, generalizations: []int{}}
	var p53 = charParser{id: 53, not: false, chars: []rune{125}, ranges: [][]rune{}}
	p135.items = []parser{&p53}
	p146.items = []parser{&p44, &p186, &p127, &p186, &p49, &p186, &p26, &p186, &p135}
	var p161 = sequenceParser{id: 161, commit: 72, allChars: true, name: "one-or-more", ranges: [][]int{{1, 1}, {1, 1}}, generalizations: []int{10}}
	var p60 = charParser{id: 60, not: false, chars: []rune{43}, ranges: [][]rune{}}
	p161.items = []parser{&p60}
	var p104 = sequenceParser{id: 104, commit: 72, allChars: true, name: "zero-or-more", ranges: [][]int{{1, 1}, {1, 1}}, generalizations: []int{10}}
	var p111 = charParser{id: 111, not: false, chars: []rune{42}, ranges: [][]rune{}}
	p104.items = []parser{&p111}
	var p155 = sequenceParser{id: 155, commit: 72, allChars: true, name: "zero-or-one", ranges: [][]int{{1, 1}, {1, 1}}, generalizations: []int{10}}
	var p98 = charParser{id: 98, not: false, chars: []rune{63}, ranges: [][]rune{}}
	p155.items = []parser{&p98}
	p10.options = []parser{&p139, &p146, &p161, &p104, &p155}
	p61.items = []parser{&p21, &p10}
	var p105 = sequenceParser{id: 105, commit: 2, allChars: false, ranges: [][]int{{0, -1}, {1, 1}}, generalizations: []int{}}
	p105.items = []parser{&p186, &p61}
	p106.items = []parser{&p61, &p105}
	var p100 = sequenceParser{id: 100, commit: 64, allChars: false, name: "choice", ranges: [][]int{{1, 1}, {0, -1}, {1, 1}, {0, -1}}, generalizations: []int{15}}
	var p171 = choiceParser{id: 171, commit: 66, name: "option", generalizations: []int{}}
	p171.options = []parser{&p88, &p8, &p174, &p106}
	var p168 = sequenceParser{id: 168, commit: 2, allChars: false, ranges: [][]int{{1, 1}, {0, -1}, {1, 1}}, generalizations: []int{}}
	var p80 = sequenceParser{id: 80, commit: 10, allChars: true, ranges: [][]int{{1, 1}, {1, 1}}, generalizations: []int{}}
	var p112 = charParser{id: 112, not: false, chars: []rune{124}, ranges: [][]rune{}}
	p80.items = []parser{&p112}
	p168.items = []parser{&p80, &p186, &p171}
	var p99 = sequenceParser{id: 99, commit: 2, allChars: false, ranges: [][]int{{0, -1}, {1, 1}}, generalizations: []int{}}
	p99.items = []parser{&p186, &p168}
	p100.items = []parser{&p171, &p186, &p168, &p99}
	p15.options = []parser{&p88, &p8, &p174, &p106, &p100}
	p46.items = []parser{&p18, &p186, &p177, &p186, &p15}
	var p164 = sequenceParser{id: 164, commit: 2, allChars: false, ranges: [][]int{{0, -1}, {1, 1}, {0, -1}}, generalizations: []int{}}
	var p71 = sequenceParser{id: 71, commit: 2, allChars: false, ranges: [][]int{{1, 1}, {0, -1}, {0, -1}, {1, 1}}, generalizations: []int{}}
	var p34 = sequenceParser{id: 34, commit: 10, allChars: true, ranges: [][]int{{1, 1}, {1, 1}}, generalizations: []int{}}
	var p180 = charParser{id: 180, not: false, chars: []rune{59}, ranges: [][]rune{}}
	p34.items = []parser{&p180}
	var p70 = sequenceParser{id: 70, commit: 2, allChars: false, ranges: [][]int{{0, -1}, {1, 1}}, generalizations: []int{}}
	p70.items = []parser{&p186, &p34}
	p71.items = []parser{&p34, &p70, &p186, &p46}
	var p163 = sequenceParser{id: 163, commit: 2, allChars: false, ranges: [][]int{{0, -1}, {1, 1}}, generalizations: []int{}}
	p163.items = []parser{&p186, &p71}
	p164.items = []parser{&p186, &p71, &p163}
	p165.items = []parser{&p46, &p164}
	var p184 = sequenceParser{id: 184, commit: 2, allChars: false, ranges: [][]int{{0, -1}, {1, 1}, {0, -1}}, generalizations: []int{}}
	var p82 = sequenceParser{id: 82, commit: 10, allChars: true, ranges: [][]int{{1, 1}, {1, 1}}, generalizations: []int{}}
	var p41 = charParser{id: 41, not: false, chars: []rune{59}, ranges: [][]rune{}}
	p82.items = []parser{&p41}
	var p183 = sequenceParser{id: 183, commit: 2, allChars: false, ranges: [][]int{{0, -1}, {1, 1}}, generalizations: []int{}}
	p183.items = []parser{&p186, &p82}
	p184.items = []parser{&p186, &p82, &p183}
	p187.items = []parser{&p182, &p186, &p165, &p184}
	p188.items = []parser{&p186, &p187, &p186}
	var b188 = sequenceBuilder{id: 188, commit: 32, allChars: false, name: "syntax", ranges: [][]int{{0, -1}, {1, 1}, {0, -1}}}
	var b186 = choiceBuilder{id: 186, commit: 2}
	var b185 = choiceBuilder{id: 185, commit: 70}
	var b17 = choiceBuilder{id: 17, commit: 66}
	var b109 = sequenceBuilder{id: 109, commit: 10, allChars: true, ranges: [][]int{{1, 1}, {1, 1}}}
	var b108 = charBuilder{}
	b109.items = []builder{&b108}
	var b170 = sequenceBuilder{id: 170, commit: 10, allChars: true, ranges: [][]int{{1, 1}, {1, 1}}}
	var b137 = charBuilder{}
	b170.items = []builder{&b137}
	var b54 = sequenceBuilder{id: 54, commit: 10, allChars: true, ranges: [][]int{{1, 1}, {1, 1}}}
	var b147 = charBuilder{}
	b54.items = []builder{&b147}
	var b64 = sequenceBuilder{id: 64, commit: 10, allChars: true, ranges: [][]int{{1, 1}, {1, 1}}}
	var b157 = charBuilder{}
	b64.items = []builder{&b157}
	var b72 = sequenceBuilder{id: 72, commit: 10, allChars: true, ranges: [][]int{{1, 1}, {1, 1}}}
	var b121 = charBuilder{}
	b72.items = []builder{&b121}
	var b19 = sequenceBuilder{id: 19, commit: 10, allChars: true, ranges: [][]int{{1, 1}, {1, 1}}}
	var b16 = charBuilder{}
	b19.items = []builder{&b16}
	var b5 = sequenceBuilder{id: 5, commit: 10, allChars: true, ranges: [][]int{{1, 1}, {1, 1}}}
	var b73 = charBuilder{}
	b5.items = []builder{&b73}
	b17.options = []builder{&b109, &b170, &b54, &b64, &b72, &b19, &b5}
	var b58 = sequenceBuilder{id: 58, commit: 72, allChars: false, name: "comment", ranges: [][]int{{1, 1}, {0, -1}, {1, 1}, {0, -1}}}
	var b43 = choiceBuilder{id: 43, commit: 74}
	var b144 = sequenceBuilder{id: 144, commit: 74, allChars: false, ranges: [][]int{{1, 1}, {0, -1}, {1, 1}, {0, -1}}}
	var b138 = sequenceBuilder{id: 138, commit: 10, allChars: true, ranges: [][]int{{1, 1}, {1, 1}, {1, 1}, {1, 1}}}
	var b42 = charBuilder{}
	var b35 = charBuilder{}
	b138.items = []builder{&b42, &b35}
	var b30 = sequenceBuilder{id: 30, commit: 10, allChars: true, ranges: [][]int{{1, 1}, {1, 1}}}
	var b166 = charBuilder{}
	b30.items = []builder{&b166}
	b144.items = []builder{&b138, &b30}
	var b90 = sequenceBuilder{id: 90, commit: 74, allChars: false, ranges: [][]int{{1, 1}, {0, -1}, {1, 1}, {1, 1}, {0, -1}, {1, 1}}}
	var b129 = sequenceBuilder{id: 129, commit: 10, allChars: true, ranges: [][]int{{1, 1}, {1, 1}, {1, 1}, {1, 1}}}
	var b158 = charBuilder{}
	var b95 = charBuilder{}
	b129.items = []builder{&b158, &b95}
	var b6 = choiceBuilder{id: 6, commit: 10}
	var b153 = sequenceBuilder{id: 153, commit: 10, allChars: false, ranges: [][]int{{1, 1}, {1, 1}, {1, 1}, {1, 1}}}
	var b101 = sequenceBuilder{id: 101, commit: 10, allChars: true, ranges: [][]int{{1, 1}, {1, 1}}}
	var b148 = charBuilder{}
	b101.items = []builder{&b148}
	var b13 = sequenceBuilder{id: 13, commit: 10, allChars: true, ranges: [][]int{{1, 1}, {1, 1}}}
	var b142 = charBuilder{}
	b13.items = []builder{&b142}
	b153.items = []builder{&b101, &b13}
	var b143 = sequenceBuilder{id: 143, commit: 10, allChars: true, ranges: [][]int{{1, 1}, {1, 1}}}
	var b83 = charBuilder{}
	b143.items = []builder{&b83}
	b6.options = []builder{&b153, &b143}
	var b89 = sequenceBuilder{id: 89, commit: 10, allChars: true, ranges: [][]int{{1, 1}, {1, 1}, {1, 1}, {1, 1}}}
	var b96 = charBuilder{}
	var b130 = charBuilder{}
	b89.items = []builder{&b96, &b130}
	b90.items = []builder{&b129, &b6, &b89}
	b43.options = []builder{&b144, &b90}
	var b31 = sequenceBuilder{id: 31, commit: 10, allChars: false, ranges: [][]int{{0, -1}, {0, 1}, {0, -1}, {1, 1}, {0, -1}, {0, 1}, {0, -1}, {1, 1}}}
	var b57 = choiceBuilder{id: 57, commit: 74}
	var b50 = sequenceBuilder{id: 50, commit: 10, allChars: true, ranges: [][]int{{1, 1}, {1, 1}}}
	var b167 = charBuilder{}
	b50.items = []builder{&b167}
	var b151 = sequenceBuilder{id: 151, commit: 10, allChars: true, ranges: [][]int{{1, 1}, {1, 1}}}
	var b114 = charBuilder{}
	b151.items = []builder{&b114}
	var b145 = sequenceBuilder{id: 145, commit: 10, allChars: true, ranges: [][]int{{1, 1}, {1, 1}}}
	var b36 = charBuilder{}
	b145.items = []builder{&b36}
	var b140 = sequenceBuilder{id: 140, commit: 10, allChars: true, ranges: [][]int{{1, 1}, {1, 1}}}
	var b122 = charBuilder{}
	b140.items = []builder{&b122}
	var b178 = sequenceBuilder{id: 178, commit: 10, allChars: true, ranges: [][]int{{1, 1}, {1, 1}}}
	var b77 = charBuilder{}
	b178.items = []builder{&b77}
	var b66 = sequenceBuilder{id: 66, commit: 10, allChars: true, ranges: [][]int{{1, 1}, {1, 1}}}
	var b37 = charBuilder{}
	b66.items = []builder{&b37}
	b57.options = []builder{&b50, &b151, &b145, &b140, &b178, &b66}
	var b141 = sequenceBuilder{id: 141, commit: 10, allChars: true, ranges: [][]int{{1, 1}, {1, 1}}}
	var b51 = charBuilder{}
	b141.items = []builder{&b51}
	b31.items = []builder{&b57, &b141, &b57, &b43}
	b58.items = []builder{&b43, &b31}
	b185.options = []builder{&b17, &b58}
	b186.options = []builder{&b185}
	var b187 = sequenceBuilder{id: 187, commit: 66, allChars: false, ranges: [][]int{{0, 1}, {0, -1}, {0, 1}, {0, 1}}}
	var b182 = sequenceBuilder{id: 182, commit: 2, allChars: false, ranges: [][]int{{1, 1}, {0, -1}}}
	var b120 = sequenceBuilder{id: 120, commit: 10, allChars: true, ranges: [][]int{{1, 1}, {1, 1}}}
	var b119 = charBuilder{}
	b120.items = []builder{&b119}
	var b181 = sequenceBuilder{id: 181, commit: 2, allChars: false, ranges: [][]int{{0, -1}, {1, 1}}}
	b181.items = []builder{&b186, &b120}
	b182.items = []builder{&b120, &b181}
	var b165 = sequenceBuilder{id: 165, commit: 66, allChars: false, ranges: [][]int{{1, 1}, {0, 1}}}
	var b46 = sequenceBuilder{id: 46, commit: 64, allChars: false, name: "definition", ranges: [][]int{{1, 1}, {0, -1}, {1, 1}, {0, -1}, {1, 1}}}
	var b18 = sequenceBuilder{id: 18, commit: 74, allChars: false, ranges: [][]int{{1, 1}, {0, -1}, {1, 1}, {0, -1}}}
	var b8 = sequenceBuilder{id: 8, commit: 72, allChars: false, name: "symbol", ranges: [][]int{{1, -1}, {1, -1}}}
	var b7 = sequenceBuilder{id: 7, commit: 10, allChars: true, ranges: [][]int{{1, 1}, {1, 1}}}
	var b154 = charBuilder{}
	b7.items = []builder{&b154}
	b8.items = []builder{&b7}
	var b24 = sequenceBuilder{id: 24, commit: 10, allChars: false, ranges: [][]int{{1, 1}, {1, 1}, {1, 1}, {1, 1}}}
	var b69 = sequenceBuilder{id: 69, commit: 10, allChars: true, ranges: [][]int{{1, 1}, {1, 1}}}
	var b162 = charBuilder{}
	b69.items = []builder{&b162}
	var b56 = choiceBuilder{id: 56, commit: 66}
	var b169 = sequenceBuilder{id: 169, commit: 72, allChars: true, name: "alias", ranges: [][]int{{1, 1}, {1, 1}, {1, 1}, {1, 1}, {1, 1}, {1, 1}, {1, 1}, {1, 1}, {1, 1}, {1, 1}}}
	var b175 = charBuilder{}
	var b68 = charBuilder{}
	var b4 = charBuilder{}
	var b22 = charBuilder{}
	var b97 = charBuilder{}
	b169.items = []builder{&b175, &b68, &b4, &b22, &b97}
	var b11 = sequenceBuilder{id: 11, commit: 72, allChars: true, name: "ws", ranges: [][]int{{1, 1}, {1, 1}, {1, 1}, {1, 1}}}
	var b150 = charBuilder{}
	var b45 = charBuilder{}
	b11.items = []builder{&b150, &b45}
	var b23 = sequenceBuilder{id: 23, commit: 72, allChars: true, name: "nows", ranges: [][]int{{1, 1}, {1, 1}, {1, 1}, {1, 1}, {1, 1}, {1, 1}, {1, 1}, {1, 1}}}
	var b136 = charBuilder{}
	var b55 = charBuilder{}
	var b33 = charBuilder{}
	var b39 = charBuilder{}
	b23.items = []builder{&b136, &b55, &b33, &b39}
	var b12 = sequenceBuilder{id: 12, commit: 72, allChars: true, name: "failpass", ranges: [][]int{{1, 1}, {1, 1}, {1, 1}, {1, 1}, {1, 1}, {1, 1}, {1, 1}, {1, 1}, {1, 1}, {1, 1}, {1, 1}, {1, 1}, {1, 1}, {1, 1}, {1, 1}, {1, 1}}}
	var b81 = charBuilder{}
	var b62 = charBuilder{}
	var b156 = charBuilder{}
	var b74 = charBuilder{}
	var b118 = charBuilder{}
	var b40 = charBuilder{}
	var b75 = charBuilder{}
	var b113 = charBuilder{}
	b12.items = []builder{&b81, &b62, &b156, &b74, &b118, &b40, &b75, &b113}
	var b29 = sequenceBuilder{id: 29, commit: 72, allChars: true, name: "root", ranges: [][]int{{1, 1}, {1, 1}, {1, 1}, {1, 1}, {1, 1}, {1, 1}, {1, 1}, {1, 1}}}
	var b76 = charBuilder{}
	var b176 = charBuilder{}
	var b107 = charBuilder{}
	var b128 = charBuilder{}
	b29.items = []builder{&b76, &b176, &b107, &b128}
	b56.options = []builder{&b169, &b11, &b23, &b12, &b29}
	b24.items = []builder{&b69, &b56}
	b18.items = []builder{&b8, &b24}
	var b177 = sequenceBuilder{id: 177, commit: 10, allChars: true, ranges: [][]int{{1, 1}, {1, 1}}}
	var b63 = charBuilder{}
	b177.items = []builder{&b63}
	var b15 = choiceBuilder{id: 15, commit: 66}
	var b88 = choiceBuilder{id: 88, commit: 66}
	var b179 = sequenceBuilder{id: 179, commit: 72, allChars: true, name: "any-char", ranges: [][]int{{1, 1}, {1, 1}}}
	var b67 = charBuilder{}
	b179.items = []builder{&b67}
	var b173 = sequenceBuilder{id: 173, commit: 72, allChars: false, name: "char-class", ranges: [][]int{{1, 1}, {0, 1}, {0, -1}, {1, 1}, {1, 1}, {0, 1}, {0, -1}, {1, 1}}}
	var b131 = sequenceBuilder{id: 131, commit: 10, allChars: true, ranges: [][]int{{1, 1}, {1, 1}}}
	var b20 = charBuilder{}
	b131.items = []builder{&b20}
	var b87 = sequenceBuilder{id: 87, commit: 72, allChars: true, name: "class-not", ranges: [][]int{{1, 1}, {1, 1}}}
	var b91 = charBuilder{}
	b87.items = []builder{&b91}
	var b110 = choiceBuilder{id: 110, commit: 10}
	var b65 = choiceBuilder{id: 65, commit: 72, name: "class-char"}
	var b1 = sequenceBuilder{id: 1, commit: 10, allChars: true, ranges: [][]int{{1, 1}, {1, 1}}}
	var b102 = charBuilder{}
	b1.items = []builder{&b102}
	var b38 = sequenceBuilder{id: 38, commit: 10, allChars: false, ranges: [][]int{{1, 1}, {1, 1}, {1, 1}, {1, 1}}}
	var b116 = sequenceBuilder{id: 116, commit: 10, allChars: true, ranges: [][]int{{1, 1}, {1, 1}}}
	var b28 = charBuilder{}
	b116.items = []builder{&b28}
	var b172 = sequenceBuilder{id: 172, commit: 10, allChars: true, ranges: [][]int{{1, 1}, {1, 1}}}
	var b123 = charBuilder{}
	b172.items = []builder{&b123}
	b38.items = []builder{&b116, &b172}
	b65.options = []builder{&b1, &b38}
	var b117 = sequenceBuilder{id: 117, commit: 72, allChars: false, name: "char-range", ranges: [][]int{{1, 1}, {1, 1}, {1, 1}, {1, 1}, {1, 1}, {1, 1}}}
	var b159 = sequenceBuilder{id: 159, commit: 10, allChars: true, ranges: [][]int{{1, 1}, {1, 1}}}
	var b115 = charBuilder{}
	b159.items = []builder{&b115}
	b117.items = []builder{&b65, &b159, &b65}
	b110.options = []builder{&b65, &b117}
	var b103 = sequenceBuilder{id: 103, commit: 10, allChars: true, ranges: [][]int{{1, 1}, {1, 1}}}
	var b132 = charBuilder{}
	b103.items = []builder{&b132}
	b173.items = []builder{&b131, &b87, &b110, &b103}
	var b3 = sequenceBuilder{id: 3, commit: 72, allChars: false, name: "char-sequence", ranges: [][]int{{1, 1}, {0, -1}, {1, 1}, {1, 1}, {0, -1}, {1, 1}}}
	var b152 = sequenceBuilder{id: 152, commit: 10, allChars: true, ranges: [][]int{{1, 1}, {1, 1}}}
	var b84 = charBuilder{}
	b152.items = []builder{&b84}
	var b52 = choiceBuilder{id: 52, commit: 72, name: "sequence-char"}
	var b32 = sequenceBuilder{id: 32, commit: 10, allChars: true, ranges: [][]int{{1, 1}, {1, 1}}}
	var b14 = charBuilder{}
	b32.items = []builder{&b14}
	var b160 = sequenceBuilder{id: 160, commit: 10, allChars: false, ranges: [][]int{{1, 1}, {1, 1}, {1, 1}, {1, 1}}}
	var b2 = sequenceBuilder{id: 2, commit: 10, allChars: true, ranges: [][]int{{1, 1}, {1, 1}}}
	var b124 = charBuilder{}
	b2.items = []builder{&b124}
	var b133 = sequenceBuilder{id: 133, commit: 10, allChars: true, ranges: [][]int{{1, 1}, {1, 1}}}
	var b47 = charBuilder{}
	b133.items = []builder{&b47}
	b160.items = []builder{&b2, &b133}
	b52.options = []builder{&b32, &b160}
	var b125 = sequenceBuilder{id: 125, commit: 10, allChars: true, ranges: [][]int{{1, 1}, {1, 1}}}
	var b48 = charBuilder{}
	b125.items = []builder{&b48}
	b3.items = []builder{&b152, &b52, &b125}
	b88.options = []builder{&b179, &b173, &b3}
	var b174 = sequenceBuilder{id: 174, commit: 66, allChars: false, ranges: [][]int{{1, 1}, {0, -1}, {1, 1}, {0, -1}, {1, 1}}}
	var b85 = sequenceBuilder{id: 85, commit: 10, allChars: true, ranges: [][]int{{1, 1}, {1, 1}}}
	var b149 = charBuilder{}
	b85.items = []builder{&b149}
	var b25 = sequenceBuilder{id: 25, commit: 10, allChars: true, ranges: [][]int{{1, 1}, {1, 1}}}
	var b79 = charBuilder{}
	b25.items = []builder{&b79}
	b174.items = []builder{&b85, &b186, &b15, &b186, &b25}
	var b106 = sequenceBuilder{id: 106, commit: 64, allChars: false, name: "sequence", ranges: [][]int{{1, 1}, {0, -1}}}
	var b61 = sequenceBuilder{id: 61, commit: 72, allChars: false, name: "item", ranges: [][]int{{1, 1}, {0, 1}, {1, 1}, {0, 1}}}
	var b21 = choiceBuilder{id: 21, commit: 10}
	b21.options = []builder{&b88, &b8, &b174}
	var b10 = choiceBuilder{id: 10, commit: 66}
	var b139 = sequenceBuilder{id: 139, commit: 64, allChars: false, name: "count-quantifier", ranges: [][]int{{1, 1}, {0, -1}, {1, 1}, {0, -1}, {1, 1}}}
	var b27 = sequenceBuilder{id: 27, commit: 10, allChars: true, ranges: [][]int{{1, 1}, {1, 1}}}
	var b9 = charBuilder{}
	b27.items = []builder{&b9}
	var b86 = sequenceBuilder{id: 86, commit: 64, allChars: false, name: "count", ranges: [][]int{{1, 1}}}
	var b92 = sequenceBuilder{id: 92, commit: 74, allChars: false, ranges: [][]int{{1, -1}, {1, -1}}}
	var b134 = sequenceBuilder{id: 134, commit: 10, allChars: true, ranges: [][]int{{1, 1}, {1, 1}}}
	var b126 = charBuilder{}
	b134.items = []builder{&b126}
	b92.items = []builder{&b134}
	b86.items = []builder{&b92}
	var b93 = sequenceBuilder{id: 93, commit: 10, allChars: true, ranges: [][]int{{1, 1}, {1, 1}}}
	var b78 = charBuilder{}
	b93.items = []builder{&b78}
	b139.items = []builder{&b27, &b186, &b86, &b186, &b93}
	var b146 = sequenceBuilder{id: 146, commit: 64, allChars: false, name: "range-quantifier", ranges: [][]int{{1, 1}, {0, -1}, {0, 1}, {0, -1}, {1, 1}, {0, -1}, {0, 1}, {0, -1}, {1, 1}}}
	var b44 = sequenceBuilder{id: 44, commit: 10, allChars: true, ranges: [][]int{{1, 1}, {1, 1}}}
	var b94 = charBuilder{}
	b44.items = []builder{&b94}
	var b127 = sequenceBuilder{id: 127, commit: 64, allChars: false, name: "range-from", ranges: [][]int{{1, 1}}}
	b127.items = []builder{&b92}
	var b49 = sequenceBuilder{id: 49, commit: 10, allChars: true, ranges: [][]int{{1, 1}, {1, 1}}}
	var b59 = charBuilder{}
	b49.items = []builder{&b59}
	var b26 = sequenceBuilder{id: 26, commit: 64, allChars: false, name: "range-to", ranges: [][]int{{1, 1}}}
	b26.items = []builder{&b92}
	var b135 = sequenceBuilder{id: 135, commit: 10, allChars: true, ranges: [][]int{{1, 1}, {1, 1}}}
	var b53 = charBuilder{}
	b135.items = []builder{&b53}
	b146.items = []builder{&b44, &b186, &b127, &b186, &b49, &b186, &b26, &b186, &b135}
	var b161 = sequenceBuilder{id: 161, commit: 72, allChars: true, name: "one-or-more", ranges: [][]int{{1, 1}, {1, 1}}}
	var b60 = charBuilder{}
	b161.items = []builder{&b60}
	var b104 = sequenceBuilder{id: 104, commit: 72, allChars: true, name: "zero-or-more", ranges: [][]int{{1, 1}, {1, 1}}}
	var b111 = charBuilder{}
	b104.items = []builder{&b111}
	var b155 = sequenceBuilder{id: 155, commit: 72, allChars: true, name: "zero-or-one", ranges: [][]int{{1, 1}, {1, 1}}}
	var b98 = charBuilder{}
	b155.items = []builder{&b98}
	b10.options = []builder{&b139, &b146, &b161, &b104, &b155}
	b61.items = []builder{&b21, &b10}
	var b105 = sequenceBuilder{id: 105, commit: 2, allChars: false, ranges: [][]int{{0, -1}, {1, 1}}}
	b105.items = []builder{&b186, &b61}
	b106.items = []builder{&b61, &b105}
	var b100 = sequenceBuilder{id: 100, commit: 64, allChars: false, name: "choice", ranges: [][]int{{1, 1}, {0, -1}, {1, 1}, {0, -1}}}
	var b171 = choiceBuilder{id: 171, commit: 66}
	b171.options = []builder{&b88, &b8, &b174, &b106}
	var b168 = sequenceBuilder{id: 168, commit: 2, allChars: false, ranges: [][]int{{1, 1}, {0, -1}, {1, 1}}}
	var b80 = sequenceBuilder{id: 80, commit: 10, allChars: true, ranges: [][]int{{1, 1}, {1, 1}}}
	var b112 = charBuilder{}
	b80.items = []builder{&b112}
	b168.items = []builder{&b80, &b186, &b171}
	var b99 = sequenceBuilder{id: 99, commit: 2, allChars: false, ranges: [][]int{{0, -1}, {1, 1}}}
	b99.items = []builder{&b186, &b168}
	b100.items = []builder{&b171, &b186, &b168, &b99}
	b15.options = []builder{&b88, &b8, &b174, &b106, &b100}
	b46.items = []builder{&b18, &b186, &b177, &b186, &b15}
	var b164 = sequenceBuilder{id: 164, commit: 2, allChars: false, ranges: [][]int{{0, -1}, {1, 1}, {0, -1}}}
	var b71 = sequenceBuilder{id: 71, commit: 2, allChars: false, ranges: [][]int{{1, 1}, {0, -1}, {0, -1}, {1, 1}}}
	var b34 = sequenceBuilder{id: 34, commit: 10, allChars: true, ranges: [][]int{{1, 1}, {1, 1}}}
	var b180 = charBuilder{}
	b34.items = []builder{&b180}
	var b70 = sequenceBuilder{id: 70, commit: 2, allChars: false, ranges: [][]int{{0, -1}, {1, 1}}}
	b70.items = []builder{&b186, &b34}
	b71.items = []builder{&b34, &b70, &b186, &b46}
	var b163 = sequenceBuilder{id: 163, commit: 2, allChars: false, ranges: [][]int{{0, -1}, {1, 1}}}
	b163.items = []builder{&b186, &b71}
	b164.items = []builder{&b186, &b71, &b163}
	b165.items = []builder{&b46, &b164}
	var b184 = sequenceBuilder{id: 184, commit: 2, allChars: false, ranges: [][]int{{0, -1}, {1, 1}, {0, -1}}}
	var b82 = sequenceBuilder{id: 82, commit: 10, allChars: true, ranges: [][]int{{1, 1}, {1, 1}}}
	var b41 = charBuilder{}
	b82.items = []builder{&b41}
	var b183 = sequenceBuilder{id: 183, commit: 2, allChars: false, ranges: [][]int{{0, -1}, {1, 1}}}
	b183.items = []builder{&b186, &b82}
	b184.items = []builder{&b186, &b82, &b183}
	b187.items = []builder{&b182, &b186, &b165, &b184}
	b188.items = []builder{&b186, &b187, &b186}

	return parse(r, &p188, &b188)
}
